### ISSUE TITLE
Network synchronises after read-only actions

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/cli#86]
The network synchronises after every action, rather than just actions which entail making changes. This makes the user wait unnecessarily. I think the syncing should be removed after these actions:
- Read metadata
- Open module folder
- Open main file

Do you agree @juliangruber that we can remove these? What would potentially be the downside of this?

**Comment by juliangruber** [comment]
> Do you agree @juliangruber that we can remove these? What would potentially be the downside of this?

I need to test this, however a potential downside is that the less time you spend on the network the less chances peers have to get data from you. Say if a peer just joined the network and wants to download your archive - in this case whether you updated something or just read doesn't make a difference to your peer.

**Comment by juliangruber** [comment]
Also it's not like we upload anything after write actions. I think the log message is the culprit. We're not really synchronizing the network, what is happening is https://github.com/p2pcommons/sdk-js#destroy

> Closes the swarm instance (if created) and the local db.

What should we print instead? `Closing peer-to-peer stack`?

**Comment by jameslibscie** [comment]
Is it otherwise possible for this to happen in the background async, so it doesn't hold up the command line? And if it's possible, how much work is it?

I don't think that users will be interested in when the connection is closed, but rather when sync occurs and when it is complete. Exactly when does the network syncing actually happen right now btw?

**Comment by juliangruber** [comment]
> I don't think that users will be interested in when the connection is closed, but rather when sync occurs and when it is complete.

There's no concept of a "complete sync" in P2P. You as a peer offer your data to the network. Anyone else can download your data if they want, but they can choose how much of it, and when.

> Is it otherwise possible for this to happen in the background async, so it doesn't hold up the command line? And if it's possible, how much work is it?

This will be possible once we have the dat daemon aka Hypergraph Desktop. Desktop will do the background seeding while the CLI is only open for a short bit. This requires the user to run Hypergraph Desktop however. And really the CLI doesn't make sense without Desktop, because otherwise your stuff won't be seeded (except if you publish it to the Vault). Does that make sense?

**Comment by jameslibscie** [comment]
Gotcha :) It does make more sense to speak in terms of "open" and "closed" rather than "start" and "complete".

So Desktop will handle the network stuff in the future, but right now CLI can handle it as well but only in a synchronous and temporary way? What can the networking in the CLI currently do? And when exactly does it do it? Do you see the swarm destroy / p2p stack closing being removed from the CLI once we have Desktop?

**Comment by juliangruber** [comment]
> What can the networking in the CLI currently do?

Basically nothing. Since the CLI is only open for a very short period of time, chances that peers can download your data are very low. Without a daemon / Desktop the CLI is only for managing content, but not networking features.

> And when exactly does it do it?

As long as the CLI is running it will offer its data over the network.

> Do you see the swarm destroy / p2p stack closing being removed from the CLI once we have Desktop?

This is up for decision...if we make the CLI a "client" for Desktop, then we could remove the p2p stuff from it completely. Then the CLI would only use Desktop's API.

Not sure if we want to couple the CLI to Desktop completely though, as it's still useful for publishing to the Vault. However the CLI on its own isn't really a p2p app, as there's no daemon. We could talk about adding a daemon to the CLI, that's independent of Desktop.

@chartgerink what do you think about coupling CLI and Desktop?

**Comment by jameslibscie** [comment]
Cool, thanks for explaining :)

What was the reasoning behind including these networking features in the first place. Is it just to test or fully implement the SDK or is this necessary for the Vault connectivity as well? If it's the former, I'd say we can leave it like this for now and probably remove it later. If it's for Vault connectivity, can we restrict network activity so it only happens on Vault publish?

**Comment by juliangruber** [comment]
If this is just about waiting after a command completes, I'm not sure this change is worth it right now.

We can easily disable networking now, but then follow and other actions requiring network need to be removed too.

**Comment by jameslibscie** [comment]
> If this is just about waiting after a command completes, I'm not sure this change is worth it right now.

Exactly. And the follow action is also about manipulating local metadata, right? So even if we remove networking from CLI, it would still have a purpose if there is a Daemon running. I will close this :)
